import 'package:flutter_test/flutter_test.dart';
import 'package:assessment_tool/models/assessment_models.dart';
import 'package:assessment_tool/data/facility_data_factory.dart';

/// Unit tests for the PreAssessment data initialization layer.
/// These tests validate FacilityDataFactory output, GeneralFacilityInfo
/// population, form step validation logic, and the structural integrity
/// of zone checklists generated by the factory for each FacilityType.
void main() {
  group('PreAssessment - FacilityDataFactory Output Validation', () {
    test(
        'Mpox ScreeningAndIsolation layout returns non-empty zones with checklists',
        () {
      final layout = FacilityDataFactory.getLayout(
          EmergencyType.mpox, FacilityType.screeningAndIsolation);
      expect(layout.zones, isNotEmpty);
      expect(layout.zones.every((z) => z.id.isNotEmpty), isTrue);
      // Every zone should have at least one checklist question
      for (var zone in layout.zones) {
        expect(zone.checklist, isNotEmpty,
            reason: 'Zone "${zone.name}" should have questions');
      }
    });

    test(
        'Mpox ExistingFacilityWithWard layout returns correct zone structure',
        () {
      final layout = FacilityDataFactory.getLayout(
          EmergencyType.mpox, FacilityType.existingFacilityWithWard);
      expect(layout.zones, isNotEmpty);
      // Should have multiple zones for a complex ward-based facility
      expect(layout.zones.length, greaterThanOrEqualTo(2));
    });

    test('Mpox StandAloneCenter layout initializes with all questions pending',
        () {
      final layout = FacilityDataFactory.getLayout(
          EmergencyType.mpox, FacilityType.standAloneCenter);
      for (var zone in layout.zones) {
        for (var q in zone.checklist) {
          expect(q.selectedCompliance, equals(ComplianceLevel.pending),
              reason:
                  'Question ${q.id} should start as pending, not ${q.selectedCompliance}');
        }
      }
    });

    test(
        'Mpox CongregateSetting layout returns valid checklist with non-empty question texts',
        () {
      final layout = FacilityDataFactory.getLayout(
          EmergencyType.mpox, FacilityType.congregateSetting);
      for (var zone in layout.zones) {
        for (var q in zone.checklist) {
          expect(q.text, isNotEmpty,
              reason: 'Question ${q.id} should have descriptive text');
        }
      }
    });

    test(
        'Every question in factory output has a valid AssessmentCategory assigned',
        () {
      final layout = FacilityDataFactory.getLayout(
          EmergencyType.mpox, FacilityType.screeningAndIsolation);
      for (var zone in layout.zones) {
        for (var q in zone.checklist) {
          expect(AssessmentCategory.values.contains(q.category), isTrue,
              reason: 'Question ${q.id} has invalid category');
        }
      }
    });

    test('Non-mpox emergency types fall back to a valid default layout', () {
      // Ebola and SARS are not yet implemented, so they should fall back
      final ebolaLayout =
          FacilityDataFactory.getLayout(EmergencyType.ebola, FacilityType.screeningAndIsolation);
      final sarsLayout =
          FacilityDataFactory.getLayout(EmergencyType.sars, FacilityType.screeningAndIsolation);

      expect(ebolaLayout.zones, isNotEmpty);
      expect(sarsLayout.zones, isNotEmpty);
    });
  });

  group('PreAssessment - GeneralFacilityInfo Population Flow', () {
    test('GeneralFacilityInfo correctly populates all demographic fields', () {
      final info = GeneralFacilityInfo()
        ..assessedDisease = 'MPOX'
        ..assessedFacilityType = 'Screening and temporary isolation for mpox'
        ..assessmentDate = DateTime.utc(2026, 5, 19)
        ..assessorName = 'Dr. Marco Rossi'
        ..assessorEmail = 'marco.rossi@who.int'
        ..assessorPhone = '+39 06 12345'
        ..country = 'Italy'
        ..region = 'Lazio'
        ..district = 'Roma'
        ..city = 'Rome'
        ..facilityAddressOrGps = '41.9028, 12.4964'
        ..facilityCode = 'IT-LAZ-001'
        ..facilityName = 'Ospedale Spallanzani';

      expect(info.assessedDisease, equals('MPOX'));
      expect(info.assessmentDate!.year, equals(2026));
      expect(info.assessorEmail, contains('@who.int'));
      expect(info.facilityAddressOrGps, contains('41.9028'));
    });

    test('Inpatient and ICU bed counts parse correctly from integer values',
        () {
      final info = GeneralFacilityInfo()
        ..inpatientBeds = 250
        ..icuBeds = 35;
      expect(info.inpatientBeds, equals(250));
      expect(info.icuBeds, equals(35));
    });

    test('Null bed counts handled safely without crash', () {
      final info = GeneralFacilityInfo();
      expect(info.inpatientBeds, isNull);
      expect(info.icuBeds, isNull);
      // Simulating int.tryParse on empty string (as the screen does)
      expect(int.tryParse(''), isNull);
      expect(int.tryParse('abc'), isNull);
    });

    test('FacilityLayout dateCreated is set to UTC on form submission', () {
      final layout = FacilityDataFactory.getLayout(
          EmergencyType.mpox, FacilityType.screeningAndIsolation);
      layout.dateCreated = DateTime.now().toUtc();
      expect(layout.dateCreated!.isUtc, isTrue);
    });

    test(
        'FacilityLayout facilityName defaults to "Unnamed Assessment" when empty',
        () {
      final layout = FacilityLayout();
      final name = layout.facilityName.isNotEmpty
          ? layout.facilityName
          : "Unnamed Assessment";
      expect(name, equals("Unnamed Assessment"));
    });
  });

  group('PreAssessment - Form Step Navigation Logic', () {
    test('Step counter increments correctly within bounds', () {
      int currentStep = 0;
      const totalSteps = 4;

      // Simulate 3 "Next" taps
      for (int i = 0; i < 3; i++) {
        if (currentStep < totalSteps - 1) currentStep++;
      }
      expect(currentStep, equals(3)); // Last step

      // Cannot go beyond last step
      if (currentStep < totalSteps - 1) currentStep++;
      expect(currentStep, equals(3)); // Still at last step
    });

    test('Step counter decrements correctly without going below 0', () {
      int currentStep = 2;

      // Simulate "Back" tap
      if (currentStep > 0) currentStep--;
      expect(currentStep, equals(1));

      if (currentStep > 0) currentStep--;
      expect(currentStep, equals(0));

      // Cannot go below 0
      if (currentStep > 0) currentStep--;
      expect(currentStep, equals(0));
    });

    test('FacilityType name mapping returns correct human-readable strings',
        () {
      String getFacilityTypeName(FacilityType type) {
        switch (type) {
          case FacilityType.screeningAndIsolation:
            return "Screening and temporary isolation for mpox";
          case FacilityType.existingFacilityWithWard:
            return "Existing Healthcare facility with mpox dedicated ward";
          case FacilityType.standAloneCenter:
            return "Mpox stand-alone treatment centre";
          case FacilityType.congregateSetting:
            return "Screening for Internally Displaced People (IDP) and refugee camps";
        }
      }

      expect(getFacilityTypeName(FacilityType.screeningAndIsolation),
          contains('Screening'));
      expect(getFacilityTypeName(FacilityType.existingFacilityWithWard),
          contains('ward'));
      expect(getFacilityTypeName(FacilityType.standAloneCenter),
          contains('stand-alone'));
      expect(getFacilityTypeName(FacilityType.congregateSetting),
          contains('IDP'));
    });
  });
}
