codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        # Our target
        target: 90%
        threshold: 2%
    patch:
      default:
        target: 90%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "lib/**/*.g.dart"
  - "lib/**/*.freezed.dart"
  - "lib/main.dart"
  - "lib/l10n/**"
  - "lib/firebase_options.dart"
  - "test/**/*"
  - "integration_test/**/*"
