// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmCWCFbUL7tjhs8GfMaJ8DykLRuhGHZnQ',
    appId: '1:77861688866:web:44bd1e7f674eae4896dc7b',
    messagingSenderId: '77861688866',
    projectId: 'whoassessmentapp',
    authDomain: 'whoassessmentapp.firebaseapp.com',
    storageBucket: 'whoassessmentapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-8hOSZCAp5Rt_6YF7eDei-M44INqVnq4',
    appId: '1:77861688866:android:0663a64c7494ca4b96dc7b',
    messagingSenderId: '77861688866',
    projectId: 'whoassessmentapp',
    storageBucket: 'whoassessmentapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOqYelzkdAJ7JfLJR_Zwt9CAWLzVGSJx0',
    appId: '1:77861688866:ios:982c89a95f0e938896dc7b',
    messagingSenderId: '77861688866',
    projectId: 'whoassessmentapp',
    storageBucket: 'whoassessmentapp.firebasestorage.app',
    iosBundleId: 'com.gabriele.whoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOqYelzkdAJ7JfLJR_Zwt9CAWLzVGSJx0',
    appId: '1:77861688866:ios:c7fd594370f6649796dc7b',
    messagingSenderId: '77861688866',
    projectId: 'whoassessmentapp',
    storageBucket: 'whoassessmentapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmCWCFbUL7tjhs8GfMaJ8DykLRuhGHZnQ',
    appId: '1:77861688866:web:7f3649222d9cd69196dc7b',
    messagingSenderId: '77861688866',
    projectId: 'whoassessmentapp',
    authDomain: 'whoassessmentapp.firebaseapp.com',
    storageBucket: 'whoassessmentapp.firebasestorage.app',
  );
}
