name: Flutter CI & Codecov

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Cache Pub dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install Dependencies
        run: flutter pub get

      # (Opzionale) Genera i file di build_runner se non sono committati
      # - name: Run Build Runner
      #   run: dart run build_runner build --delete-conflicting-outputs

      - name: Run Tests with Coverage
        run: flutter test --coverage test/unit test/widget --concurrency=1
        timeout-minutes: 10

      - name: Remove Generated Files from Coverage
        if: always()
        run: dart run remove_from_coverage -f coverage/lcov.info -r "\.g\.dart$"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        if: always()
        with:
          files: coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
